export const GET_DOGS = "GET_DOGS";
export const GET_NAME_DOGS = "GET_NAME_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const GET_FILTER_CREATE = "GET_FILTER_CREATE";
export const GET_FILTER_TEMPERAMENTS = "GET_FILTER_TEMPERAMENTS";
export const ORDER = "ORDER";
